### ISSUE TITLE
Codex infrastructure

### ISSUE THREAD

**Issue by dryajov** [status-im/infra-codex#1]
@jakubgs We've looked at different options and specifically Hetzner and for our needs we believe that the `AX41-NVMe` is the best option. The specs for that are:

```
AMD Ryzen™ 5 3600 CPU
6 cores / 12 threads @ 3.6 GHz
Generation: Matisse (Zen 2)
RAM 64 GB DDR4 RAM
Drives 2 x 512 GB NVMe SSD
```

We'd need 12 of these boxes and we're targeting around 100 Codex instances total, which means that we'll be running multiple instances per box. In addition to the Codex nodes we'll be running a Geth node per box (in a POA setup). 

So to summarize:

- 12 Hetzner AX41-NVMe (or comparable)
- 10 Codex instances per box
- 1 Geth instance per box

The Codex repo is located in https://github.com/status-im/nim-dagger, I'll be updating the readme with instructions on how to run it shortly, or you can ping me directly if you need assistance.

@markspanbroek @cskiraly @michaelsbradleyjr @emizzle @Menduist

**Comment by jakubgs** [comment]
All I can do for now is configure the two hosts we have leftover from Pyrmont testnet:
https://github.com/status-im/infra-codex/blob/2cc52367f22e72eecdadb6acbfb5e248d1c900dc/ansible/inventory/test#L3-L5
Here's the SSH access I configured for now:
https://github.com/status-im/infra-codex/blob/2cc52367f22e72eecdadb6acbfb5e248d1c900dc/ansible/group_vars/all.yml#L13-L15
I gave both @dryajov and @Menduist admin rights so they can try to set up something themselves.

**Comment by jakubgs** [comment]
I see there has been work ongoing in a separate branch: https://github.com/status-im/infra-codex/commits/tanguybranch

And there's an Ansible role repo also: https://github.com/status-im/infra-role-nim-codex

The question is, what next? Do we want to expand the `codex.tests` fleet or leave it as is and deploy bigger `codex.prod`?

**Comment by jakubgs** [comment]
So here are the next steps for `codex.test` fleet:

1. Merge https://github.com/status-im/infra-codex/pull/2
2. Clean the changes up to match other fleets
3. Refactor and cleanup the [infra-role-nim-codex](https://github.com/status-im/infra-role-nim-codex) role
4. Move Geth accounts and passwords to BitWarden
5. Configure logs and metrics collection

Once we have that going well we can start thinking about a `codex.prod` fleet.

**Comment by jakubgs** [comment]
Did some cleanup of naming in the role and fleet:

- https://github.com/status-im/infra-role-nim-codex/commit/d9e29e70 - add nim_ prefix to codex_ variables
- https://github.com/status-im/infra-role-nim-codex/commit/de582958 - change default name of node to start with nim-codex
- https://github.com/status-im/infra-codex/commit/be79fbf9 - update Codex role variable prefixes to include nim_
- https://github.com/status-im/infra-codex/commit/aed4b899 - update service names to use nim- prefix

So now the service are called `nim-codex-01` and `nim-codex-02` and so on:
```
admin@metal-01.he-eu-hel1.codex.test:~ % s list-units -a 'nim-codex-*'
  UNIT                 LOAD   ACTIVE SUB     DESCRIPTION 
  nim-codex-01.service loaded active running Codex (main)
  nim-codex-02.service loaded active running Codex (main)

admin@metal-02.he-eu-hel1.codex.test:~ % s list-units -a 'nim-codex-*'
  UNIT                 LOAD   ACTIVE SUB     DESCRIPTION 
  nim-codex-01.service loaded active running Codex (main)
  nim-codex-02.service loaded active running Codex (main)
```

**Comment by jakubgs** [comment]
More fixes for the role:

- https://github.com/status-im/infra-role-nim-codex/commit/d72b5bdc - enable creating consul service definition
- https://github.com/status-im/infra-role-nim-codex/commit/ed2ba6e6 - service: uncomment log level flag, drop log format
- https://github.com/status-im/infra-role-nim-codex/commit/cd32e684 - build: switch build log level to DEBUG
- https://github.com/status-im/infra-role-nim-codex/commit/d8adbf61 - build: fix names of binaries to start with nim_codex
- https://github.com/status-im/infra-role-nim-codex/commit/24c447a2 - metrics are not supported yet, drop variables
- https://github.com/status-im/infra-role-nim-codex/commit/ac1ecf21 - consul: add healthcheck to service definition

Now we have consul services properly defined:
```
admin@metal-01.he-eu-hel1.codex.test:~ % c | grep codex
build-nim-codex-01-timer  build-nim-codex-01-timer-check  script  passing
build-nim-codex-02-timer  build-nim-codex-02-timer-check  script  passing
nim-codex-01              nim-codex-01                    http    passing
nim-codex-02              nim-codex-02                    http    passing
```
![image](https://user-images.githubusercontent.com/2212681/162999170-eba43c40-f5c7-44af-bfe9-5f6e1cf97755.png)

**Comment by jakubgs** [comment]
Next step is to put some automation for deploying account to Geth nodes and setting public keys.

Some issues:

* POA accounts are special and should be kept separate
* Codex nodes get one public key for one account from Geth
* Each get instance could have all keys, should work fine
* Current geth role has no support for deploying multiple accounts
* Handling many account JSON files in BitWarden would be very manual

We could do something similar to what nimbus beacon node roles use to deploy validators. Meaning, keep them in some kind of tarball. But that might require a separate Ansible role for deploying them, like [infra-role-dist-validators](https://github.com/status-im/infra-role-dist-validators).

**Comment by jakubgs** [comment]
Improved list of public keys added by @Menduist:

- https://github.com/status-im/infra-codex/commit/8a3ee26c - Add new public keys
- https://github.com/status-im/infra-codex/commit/879af5e2 - move large list of public keys to separate files

**Comment by jakubgs** [comment]
Two small fixes for the service:

- https://github.com/status-im/infra-role-nim-codex/commit/a902c8c6 - service: fix name of log level flag
- https://github.com/status-im/infra-role-nim-codex/commit/d6433ac6 - service: fix name of codex binary

I'm going to work on deploying the keys tomorrow. Was busy with presentation today.

**Comment by jakubgs** [comment]
This is something new:
```
repo/vendor/nim-chronos/chronos/srcloc.nim(30, 1) Hint: 'Defect' is declared but not used [XDeclaredButNotUsed]
repo/vendor/nim-chronos/chronos/asyncfutures2.nim(503, 1) Hint: 'Defect' is declared but not used [XDeclaredButNotUsed]
repo/vendor/nim-chronos/chronos/srcloc.nim(30, 1) Hint: 'Defect' is declared but not used [XDeclaredButNotUsed]
repo/vendor/nim-chronos/chronos/srcloc.nim(30, 1) Hint: 'Defect' is declared but not used [XDeclaredButNotUsed]
repo/vendor/nim-chronos/chronos/srcloc.nim(30, 1) Hint: 'Defect' is declared but not used [XDeclaredButNotUsed]
repo/vendor/nim-chronos/chronos/srcloc.nim(30, 1) Hint: 'Defect' is declared but not used [XDeclaredButNotUsed]
repo/vendor/nim-chronos/chronos/asyncmacro2.nim(185, 23) Hint: 'Exception' is declared but not used [XDeclaredButNotUsed]
repo/vendor/nim-chronos/chronos/srcloc.nim(30, 1) Hint: 'Defect' is declared but not used [XDeclaredButNotUsed]
repo/vendor/nim-chronos/chronos/timer.nim(325, 1) Hint: 'Defect' is declared but not used [XDeclaredButNotUsed]
repo/vendor/nim-chronos/chronos/asyncfutures2.nim(503, 1) Hint: 'Defect' is declared but not used [XDeclaredButNotUsed]
repo/vendor/nim-chronos/chronos/srcloc.nim(30, 1) Hint: 'Defect' is declared but not used [XDeclaredButNotUsed]
repo/vendor/nim-chronos/chronos/asyncmacro2.nim(185, 23) Hint: 'Exception' is declared but not used [XDeclaredButNotUsed]
repo/vendor/nim-chronos/chronos/srcloc.nim(30, 1) Hint: 'Defect' is declared but not used [XDeclaredButNotUsed]
repo/dagger/blockexchange/engine.nim(159, 60) template/generic instantiation of `async` from here
repo/dagger/blockexchange/engine.nim(166, 9) template/generic instantiation of `debug` from here
repo/vendor/nim-chronicles/chronicles.nim(359, 10) template/generic instantiation of `log` from here
repo/dagger/blockexchange/engine.nim(32, 12) template/generic instantiation of `expandItIMPL` from here
repo/vendor/nim-chronicles/chronicles/log_output.nim(740, 39) template/generic instantiation of `setProperty` from here
repo/vendor/nim-chronicles/chronicles/log_output.nim(677, 10) template/generic instantiation of `[]=` from here
repo/vendor/nim-chronicles/chronicles/log_output.nim(652, 15) template/generic instantiation of `writeField` from here
repo/vendor/nim-json-serialization/json_serialization/writer.nim(72, 4) template/generic instantiation of `writeValue` from here
repo/vendor/nim-json-serialization/json_serialization/writer.nim(224, 10) template/generic instantiation of `enumInstanceSerializedFields` from here
repo/vendor/nim-json-serialization/json_serialization/writer.nim(227, 8) template/generic instantiation of `writeFieldIMPL` from here
repo/vendor/nim-serialization/serialization/object_serialization.nim(192, 9) template/generic instantiation of `writeValue` from here
repo/vendor/nim-json-serialization/json_serialization/writer.nim(233, 12) Error: Failed to convert to JSON an unsupported type: MultiCodec
```
@Menduist any ideas? This is https://github.com/status-im/nim-codex/commit/b88561e0903503e897d70deef6587697677a16b6.

**Comment by dryajov** [comment]
Ah yeah, we're missing serializers for several types for JSON logging, for now you can workaround it by running with `-d:chronicles_log_level=INFO`.

**Comment by jakubgs** [comment]
Some more flag fixes:

- https://github.com/status-im/infra-role-nim-codex/commit/2ef3aff9 - service: fix name of service template
- https://github.com/status-im/infra-role-nim-codex/commit/6c88011b - service: fix listening port and address flags
- https://github.com/status-im/infra-role-nim-codex/commit/6d14fb1c - service: add --udp-port flag to set discovery port
- https://github.com/status-im/infra-codex/commit/09b819f4 - codex.test: avoid clashes of Codex discovery port

**Comment by jakubgs** [comment]
I renamed the keys you uploaded to just be named after public keys:
```
admin@metal-01.he-eu-hel1.codex.test:~/keystore % ls | wc -l
admin@metal-01.he-eu-hel1.codex.test:~/keystore % rename -v 's/UTC--.*--/0x/' ./*
```
And now I can see which keys are for POA:
```
admin@metal-01.he-eu-hel1.codex.test:~ % ls keystore | grep -v -f publickeys
0x15641b0ec20db6b271af3db21e56a9a64eabb69c
0x5b7d8b89c3db49ffbb428bb4988c38a6fe6a5843
0x65ff54a53d45b83f2d9bb81f83a70dab1c86007a
0xedcbbfc8b785aa3ada3d7e8cc06a3ec1aa50676b
```

**Comment by Menduist** [comment]
Added the new parameters (geth & discovery):
https://github.com/status-im/infra-role-nim-codex/commit/40271d7bea1f248d65f945966ee164a885d9b24c
https://github.com/status-im/infra-codex/commit/e1d5f000c5a128d9d7b6635ef1ba2df5611bb1b2

And a small fix, codex keeps reverting the data folder permissions to 0700:
https://github.com/status-im/infra-role-nim-codex/commit/0f41e34cd354ed5cd8470ba135fe18b30769b568

**Comment by jakubgs** [comment]
Looks good.

**Comment by jakubgs** [comment]
For reference, we fixed the Geth setup on Sunday: https://github.com/status-im/infra-codex/commit/8335563a

**Comment by jakubgs** [comment]
I consider this done. If we need more hosts in the future we can handle that in a new issue.
