### ISSUE TITLE
Decommission 2 Codex related hosts

### ISSUE THREAD

**Issue by veaceslavdoina** [status-im/infra-codex#5]
During last meeting with @jakubgs we discussed about [2 Codex related hosts](https://github.com/status-im/infra-codex/blob/master/ansible/inventory/test)

```shell
metal-01.he-eu-hel1.codex.test.statusim.net
metal-02.he-eu-hel1.codex.test.statusim.net
```
I've [asked our Codex Developers](https://discord.com/channels/895609329053474826/963349623714504784/1210539840685215774) if we still need them, but looks like they are not used and not required anymore.

Can you please check if they are not re-purposed already and if not, we can decommission them.

Hopefully we can do that before next billing cycle.

**Comment by jakubgs** [comment]
Thanks for checking this. The earliest we can decomission is middle of March:

![image](https://github.com/status-im/infra-codex/assets/2212681/2ef1be94-ee7a-483b-871c-9c5a91527ad8)

**Comment by jakubgs** [comment]
I think I'm going to reuse one of the hosts for backups.

**Comment by jakubgs** [comment]
I have cancelled and scrubbed the NVMes of AX41-NVMe #1485918 (`metal-01.he-eu-hel1.codex.test`) but kept AX41-NVMe #1485916 (`metal-02.he-eu-hel1.codex.test`) for reuse. Added a warning to repo readme:

- [`infra-codex#8e3a59ef`](https://github.com/status-im/infra-codex/commit/8e3a59ef) - readme: add warning about legacy repository

And will archive this repository.
